### ISSUE TITLE
Python 3.9+ ?

### ISSUE THREAD

**Issue by kikohs** [ohollo/chord-extractor#1]
Hi,
I would like to try your library but the setup.py forces python to be less than 3.9.
It is really the case? Can you bump to <4.0 ?
Thank you

**Comment by ohollo** [comment]
Hi @kikohs , thanks for flagging this. Yes, will look into this in the coming days, and if it's fairly trivial will implement.

**Comment by ljfreelancer88** [comment]
I'm using python3.9 too and tried `pip install chord-extractor` but I got this `ERROR: Could not find a version that satisfies the requirement chord-extractor (from versions: none)
ERROR: No matching distribution found for chord-extractor`

Thank you in advance.

**Comment by Daniel-WD** [comment]
Hi @ohollo, is there any update on this?

**Comment by ohollo** [comment]
I have now released the package so that it is usable with Python 3.9. Versions beyond that involve more involved changes of dependency versions, so haven't done this for now, but will address this soon hopefully (or any PRs are welcome to make these kinds of improvements). Closing the ticket.
