### ISSUE TITLE
Possible to match chord change with beat?

### ISSUE THREAD

**Issue by tuanha2000vn** [ohollo/chord-extractor#3]
Hi, thank for the terrific package.

Chord Extractor can retrieve correct chord most of the time. However the timing is still not really accurate.

I've monitor the chord change with librosa beat tracker and notice a slight incorrect value of the time when chord changed. Sometime the timing is 1 or more beat before/after the chord actually changed.

Can you improuve that part?

Thank you.

**Comment by ohollo** [comment]
Hi, apologies for the delayed reply. The library that chord-extractor delegates to- Chordino - is responsible for timings (and the chord classifications that come with them), so it is tricky to influence unless Chordino has a parameter which influences this (I'm unsure there is one).
